version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/var/www/html/

  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  web:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./backend:/var/www/html/
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html/

  db:
    build:
      context: .
      dockerfile: ./infra/mysql/Dockerfile
    volumes:
      - db-store:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=phper
      - PMA_PASSWORD=secret
    ports:
      - 8890:80
    volumes:
      - pma-session-store:/sessions

volumes:
  db-store:
  pma-session-store:
